name: bbo_traingui
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pyqt
  - matplotlib
  - numpy
  - pip:
    - imageio[pyav]>=2.26
    - bbo_svidreader
    - bbo-calibcamlib
    - bbo-ccvtools
    - bbo-acm-traingui
