name: bbo_acm-traingui
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pyqt=5.9.2
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pip:
    - bbo-calibcamlib
    - bbo-ccvtools
    - bbo-acm-traingui
